### ISSUE TITLE
Greetings from me

### ISSUE THREAD

**Issue by rizal1919** [kresnasatya/laravel-case#1]
Hi, nice to see your Kresna's Blog. I'm curious actually.

May I know how did you deploy your web app with the .me domain name?
Maybe you could share some references or tutorials that I could follow. I want to learn how to deploy a web app.
I have deployed my app in Heroku, but since on the 28th Nov, the Heroku free plan will be deleted I should find another one. 
You can check it here https://my-studios.herokuapp.com

Thank you.

**Comment by kresnasatya** [comment]
Hi @rizal1919, thanks for reach out.

Here's tech stack to build my personal site (https://kresna.me):

- Domain in Namecheap. Of course you can buy .me domain in anywhere.
- Netlify as hosting my site because my site is static site.
- For my personal site theme I'm using Hugo with https://github.com/adityatelange/hugo-PaperMod/
- I must change DNS from Namecheap to Netlify DNS. Please see: https://dev.to/easybuoy/setting-up-domain-with-namecheap-netlify-1a4d

That's from me. I will close the issue but feel free to continue our conversation here. :)
